#!/bin/bash

module purge
module load sierra
module load seacas

# previously ran with 16 processors
# PROCS=16
#
# skybridge has 16 cores per node
# 10 nodes = 160 processors
#
# eclipse has 36 cores per node
# 10 nodes = 360 processors
#
# attaway has 36 cores per node
# 10 nodes = 360 processors
#
PROCS=160
# PROCS=320
# PROCS=336

# geometry and mesh file
# GFILE="../geometry/bob-1mm-5kg-helmet2-hemi.g"
# GFILE="/projects/sibl/data/bob-1mm-5kg-helmet-hemi/bob-1mm-5kg-helmet2-hemi.g"
# GFILE="/projects/sibl/data/bob-1mm-5kg-helmet-hemi/bob-1mm-5kg-helmet2-hemi.g"
# GFILE="../../geometry/bob-1mm-5kg-helmet2-hemi.g"
# GFILE="../../geometry/a001/a001.e"
# GFILE="../../geometry/sphere/spheres_resolution_2.exo"
# GFILE="../../geometry/sphere/spheres_resolution_3.exo"
GFILE="../../geometry/sphere/spheres_resolution_4.exo"

decomp --processors $PROCS $GFILE

# sierra solid mechanics input file
# IFILE="bob-1mm-5kg-helmet2-0305-hemi-066b.i"
# IFILE="bob067.i"
# IFILE="bob068.i"
# IFILE="a001.i"
# IFILE="sr2.i"
# IFILE="sr3.i"
IFILE="sr4.i"

# queues
# https://wiki.sandia.gov/pages/viewpage.action?pageId=1359570410#SlurmDocumentation-Queues
# short can be used for nodes <= 40 and wall time <= 4:00:00 (4 hours)
# batch, the default queue, wall time <= 48 h 
# long, wall time <= 96 h, eclipse 256 nodes

# https://wiki.sandia.gov/display/OK/Slurm+Documentation
# over 4 hours, then need to remove 'short' from the --queue-name
#
# sierra -T 00:20:00 --queue-name batch,short --account FY180042 -j $PROCS --job-name $IFILE --run adagio -i $IFILE
sierra -T 04:00:00 --queue-name batch,short --account FY180042 -j $PROCS --job-name $IFILE --run adagio -i $IFILE
# sierra -T 06:00:00 --queue-name batch --account FY180042 -j $PROCS --job-name $IFILE --run adagio -i $IFILE
# sierra -T 24:00:00 --queue-name batch --account FY180042 -j $PROCS --job-name $IFILE --run adagio -i $IFILE
#
# historical:
#
# --post tells sierra to recombine all the exodus files
# sierra -T 04:00:00 --queue-name batch,short --account FY180042 -j $PROCS --job-name $IFILE --run --post adagio -i $IFILE
# sierra -T 4:30:00 --queue-name batch,short --account FY180042 -j $PROCS --job-name $IFILE --run --post adagio $IFILE
# sierra -T 4:00:00 --queue-name batch,short --account FY180042 -j $PROCS --job-name vox_0.1cm_p --run --post adagio -i smooth_0.1cm.i
# sierra --queue-name batch --account FY180042 -j 16 --job-name vox_0.1cm_p --pre --run --post adagio -i vox_0.1cm.i 
# sierra --queue-name batch --account FY180042 -j 16 --job-name vox_0.1cm_p --run --post adagio -i vox_0.1cm.i 
# sierra --queue-name batch --account FY180042 -j 16 --job-name vox_0.1cm_p --run --post adagio -i vox_0.1cm.i -T 4:00:00
# sierra --time 04:00:00 --queue-name batch --account FY180042 -j 16 --job-name vox_0.1cm_p --run --post adagio -i vox_0.1cm.i 
# sierra -T 04:00:00 --queue-name batch --account FY180042 -j 16 --job-name vox_0.1cm_p --run --post adagio -i vox_0.1cm.i 
#sierra -T 12:00:00 --queue-name batch --account FY180100 -j 128 --job-name bob_066 --run --post adagio -i bob-1mm-5kg-helmet2-0305-hemi-066b.i
#sierra -T 24:00:00 --queue-name batch --account FY180100 -j 128 --job-name bob_065d --pre --run --post adagio -i bob-1mm-5kg-helmet2-0305-hemi-065d.i
#sierra -T 1:00:00 --account FY139077 -j 40 --job-name versa_void --post adagio -i 4inch_sce.i
#sierra presto_itar -i 3inchOD_Ogive_32lb_Perforation.i --PROJTASK=FY128666 -j 8 --jobName=presto --pre --run --post -T 8:00:00 
#sierra presto -i 3inchOD_Ogive_32lb_Perforation.i -j 8 --pre --run --post --T=4:00:00 

