# ------------------------------------------------------------------------------
# The autotwin.mesh Python module, version 0.0.7,
# https://github.com/autotwin/mesh/
# autogenerated this file on 2024-06-07_UTC_17_07_01_024327
# from the yml recipe file:
# a001.yml
# ------------------------------------------------------------------------------
BEGIN SCULPT
  nelx = 151
  nely = 185
  nelz = 155
  xscale = 0.1
  yscale = 0.1
  zscale = 0.1
  xtranslate = 0.0
  ytranslate = 0.0
  ztranslate = 0.0
  gen_sidesets = variable
  stair = 1
  input_spn = /Users/chovey/scratch/ixi/IXI012-HH-1211-T1_large.spn
  exodus_file = a001
  spn_xyz_order = 0
END SCULPT
